---
platform: linux
image: docker:///concourse/static-golang

params:
  S3_TESTING_ACCESS_KEY_ID:
  S3_TESTING_SECRET_ACCESS_KEY:
  S3_TESTING_BUCKET:
  S3_VERSIONED_TESTING_BUCKET:
  S3_TESTING_REGION:

inputs:
  - name: s3-resource
    path: gopath/src/github.com/dgodd/ssh-resource

run:
  path: gopath/src/github.com/dgodd/ssh-resource/scripts/test
